# config/doctrine/Product.orm.yml
App\Entity\Title:
    type: entity
    repositoryClass: App\Repository\TitleRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        label:
            type: string
            length: 100
            nullable: false